services:
  db:
    image: mysql
    container_name: review-everything-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: review_everything_owner
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: review_everything
  app:
    image: review-everything/app
    container_name: review-everything
    depends_on:
      - db
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/review_everything
    ports:
      - 8080:8080