services:
  mysql:
    image: mysql
    container_name: review-everything-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: review_everything-owner
      MYSQL_PASSWORD: review_everything
      MYSQL_DATABASE: review_everything_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 20s
      retries: 10
  api:
    image: review-everything/app
    container_name: review-everything-api
    depends_on:
      mysql: 
          condition: service_healthy
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/review_everything_db
    ports:
      - 8080:8080
    
